name: FE CI with npm

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node 20.10.0
        uses: actions/setup-node@v2
        with:
          node-version: 20.10.0
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit
